server:
    port: 8080
    address: 
    error:
      path: /error 
    servlet:
      context-path: /
      session:
        timeout: 99

management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      base-path: /admin

spring:
  profiles: desktop

  session:
    store-type: none

  security:
    user:
      password: password

